spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gharkaKhaana
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  ai:
    openai:
      api-key: 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
      chat:
        model: gpt-3.5-turbo
        options:
          temperature: 0.7
          max-tokens: 1000

openai:
  api-key: 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
